### ISSUE TITLE
Cannot generate code when running skbuild without github auth

### ISSUE THREAD

**Issue by MSAdministrator** [skema-dev/skemabuild#6]
## Description

I am attempting to use `skbuild` cli to generate code and I am unable without having Github auth configured.

Here's an example proto `example.proto`

```
syntax = "proto3";
// Generated by skemabuild. DO NOT EDIT.
package appomni.detection.protos;

// you can also manually replace with your go_package address as below:
// option go_package="github.com/<your_github_name>/<repo_name>/<path_in_repo>/appomni.detection.protos/grpc-go";
option go_package="test/test;

import "google/api/annotations.proto";
import "validate/validate.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

// User Defined Protobuf Code Section
service EnrichmentOrchestrator {
    rpc Heathcheck (HealthcheckRequest) returns (HealthcheckResponse){
        option (google.api.http) = {
          get: "/api/healthcheck"
        };
    }

    rpc Helloworld (HelloworldRequest) returns (HelloworldResponse) {
        option (google.api.http) = {
            post: "/api/helloworld"
            body: "*"
        };
    };}

message HealthcheckRequest {
}

message HealthcheckResponse {
    string result = 1;
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        example: "{\"result\": \"ok\"}"
    };
}

message HelloworldRequest {
    string msg = 1 [(validate.rules).string.min_len = 3];
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        example: "{\"msg\": \"hello world\"}"
    };
}

message HelloworldResponse {
    string msg = 1;
    string code = 2;
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        example: "{\"msg\": \"hello world from server\", \"code\":\"0\"}"
    };
}
```

Using this along with the yaml config `example.yaml`

```
api:
  proto: example.proto
  stubs:
    - grpc-go
    - openapi
  version: v0.0.1
  path: https://github.com/msadministrator/test

service:
  template:
    models:
      - user
      - message
    values:
      - mysql_server_name: mysql-svc
      - mysql_password: abcd1234
      - grpc_port: "9991"
      - http_port: "9992"
```

When running `skbuild -f example.yaml` only generates a handful of files and does not generate the server or client code - just the generated protobufs.

Any help is appreciated.
